FROM odoo:17.0 AS development

# Set the user to use when running this image
USER odoo

# Make port 8069 available to the world outside this container
EXPOSE 8069

# Set the default command to run when starting the container
CMD ["odoo", "-i base"]
